# -*- coding: utf-8 -*-
"""visualizing_gender_ratio_in_pie_chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EweGDFfpakTSl2CwvzO1Om63j3KDjdz6

한글 폰트 사용하기
"""

!apt-get update -qq
!apt-get install fonts-nanum* -qq

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings(action='ignore')

path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf' # 나눔 고딕
font_name = fm.FontProperties(fname=path, size=10).get_name() # 기본 폰트 사이즈 : 10
plt.rc('font', family=font_name)
plt.rcParams['axes.unicode_minus']=False
fm._rebuild()

"""# 우리 동네 인구 구조를 파이 차트로 나타내기

`pie()` 함수
"""

import matplotlib.pyplot as plt
plt.pie([10,20])
plt.show()

"""동그란 원 그리기"""

import matplotlib.pyplot as plt
size = [2441, 2312, 1031, 1233]
plt.axis('equal') 
label = ['A형','B형','AB형', 'O형']
plt.pie(size, labels=label, autopct = '%.1f%%')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
size = [2441, 2312, 1031, 1233]                   # 혈액형 별 데이터
label = ['A형','B형','AB형', 'O형']                 # 혈액형 레이블
plt.axis('equal')                                 # 파이 차트를 동그란 원으로 그리기
plt.pie(size, labels = label, autopct = '%.1f%%') # 비율 및 범례 추가
plt.legend()
plt.show()

import matplotlib.pyplot as plt
size = [2441, 2312, 1031, 1233]
label = ['A형','B형','AB형', 'O형']
color = ['darkmagenta', 'deeppink', 'hotpink', 'pink']
plt.axis('equal')
plt.pie(size, 
        labels = label,
        autopct = '%.2f%%',       # 비율을 소수점 셋째자리에서 반올림
        explode = (0, 0, 0.1, 0), # AB형을 0.1만큼 돌출
        colors = color)
plt.legend()
plt.show()

"""matplotlib 라이브러리에서 사용할 수 있는 다양한 색의 이름

## 제주도의 성별 인구 비율 표현하기
"""

import csv
f = open('gender.csv', encoding='cp949')
data = csv.reader(f)

size = []

name = input('찾고 싶은 지역의 이름을 알려주세요 : ')
for row in data :
    if name in row[0] :
        m = row[1]
        f = row[104]
        break
size.append(m)
size.append(f)

print(f"{name}에는 남자가 {size[0]}명, 여자가 {size[1]}명이 살고 있습니다.")

import csv
f = open('gender.csv', encoding='cp949')
data = csv.reader(f)

size = []

name = input('찾고 싶은 지역의 이름을 알려주세요 : ')
for row in data :
    if name in row[0] :
        m = row[1]
        f = row[104]
        break
size.append(m)
size.append(f)

import matplotlib.pyplot as plt
color = ['crimson', 'darkcyan']
plt.axis('equal')
plt.pie(size, 
        labels = ['남','여'], 
        autopct ='%.1f%%', 
        colors = color, 
        startangle =90)       # 파이 차트의 시작 각도를 반시계방향으로 90도 이동하여 12시 정각 위치에서 그래프가 시작됨
plt.title(name + ' 지역의 남녀 성별 비율')
plt.show()

