# -*- coding: utf-8 -*-
"""visualizing_the_population_structure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bMWlax6A10L2Xi8XWuHWpkrqYGZvPXT

# 우리 동네 인구 구조 시각화하기

age.csv 출력해보기
"""

import csv

f = open('age.csv', encoding='cp949')
data = csv.reader(f)
 
for row in data :
    print(row)

"""신도림동의 data 출력하기"""

import csv

f = open('age.csv', encoding='cp949')
data = csv.reader(f)
 
for row in data :
    if row[0] == "서울특별시 구로구 신도림동(1153051000)":
        print(row)

"""파이썬 `in` 사용법"""

print('신도림' in '서울특별시 구로구 신도림동(1153051000)')
print('1153' in '서울특별시 구로구 신도림동(1153051000)')
print('()' in '서울특별시 구로구 신도림동(1153051000)')

"""`in` 사용해서 신도림동 data 출력하기"""

import csv
f = open('age.csv', encoding="cp949")
data = csv.reader(f)

for row in data :
    if '신도림' in row[0] :
        print(row)

"""0세부터 100세 이상까지의 인구를 각각 출력"""

import csv
f = open('age.csv', encoding="cp949")
data = csv.reader(f)

for row in data :
    if '신도림' in row[0] :
        for i in row[3:] :
            print(i)

"""0세부터 100세 이상까지의 인구를 리스트에 저장"""

import csv
f = open('age.csv', encoding="cp949")
data = csv.reader(f)
result = []
for row in data :
    if '신도림' in row[0] :
        for i in row[3:] :
            result.append(int(i))
print(result)

"""그래프로 나타내기"""

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.plot(result)
plt.show()

