# -*- coding: utf-8 -*-
"""visualizing_population_structure_in_various_ways.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOaHY0hnp9Jp70JDSSGJr1T1W1C-LiQc

# 인구 구조를 다양한 형태로 시각화하기

한글 폰트 사용을 위한 코드
"""

!apt-get update -qq
!apt-get install fonts-nanum* -qq

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import warnings
warnings.filterwarnings(action='ignore') 

path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf' # 나눔 고딕
font_name = fm.FontProperties(fname=path, size=10).get_name() # 기본 폰트 사이즈 : 10
plt.rc('font', family=font_name)
plt.rcParams['axes.unicode_minus']=False
fm._rebuild()

"""## `bar()` 함수로 막대그래프 그리기"""

import matplotlib.pyplot as plt
plt.bar([0,1,2,4,6,10], [1,2,3,5,6,7])
plt.show()

import matplotlib.pyplot as plt
plt.bar(range(7), [1,2,3,5,6,7,100])
plt.show()

import csv
f = open('age.csv', encoding="cp949")
data = csv.reader(f)

result = []
for row in data :
    if '신도림' in row[0] :
        for i in row[3:] :
            result.append(int(i))
            
import matplotlib.pyplot as plt 
plt.style.use('ggplot')
plt.bar(range(101), result)
plt.show()

"""## `barh()` 함수로 막대그래프 그리기"""

import csv
f = open('age.csv', encoding="cp949")
data = csv.reader(f)

result = []
for row in data :
    if '신도림' in row[0] :
        for i in row[3:] :
            result.append(int(i))
            
import matplotlib.pyplot as plt
#plt.figure(figsize = (10,5), dpi=300)            
plt.barh(range(101), result)
plt.show()

"""## 항아리모양 그래프 그리기"""

import csv
f = open('gender.csv', encoding="cp949")
data = csv.reader(f)
m = []
f = []
for row in data :
    if '신도림' in row[0] :
        for i in range(0,101) :
            m.append(int(row[i+3]))
            f.append(int(row[i+106]))

import matplotlib.pyplot as plt
plt.barh(range(101), m)
plt.barh(range(101), f)
plt.show()

import csv
f =open('gender.csv', encoding="cp949")
data = csv.reader(f)
m = []
f = []
for row in data :
    if'신도림'in row[0] :
        for i in row[3:104] : 
            m.append(-int(i)) # 마이너스 부호를 넣어서 음수로 변경
        for i in row[106:] :
            f.append(int(i))

import matplotlib.pyplot as plt
plt.barh(range(101), m, color='y')
plt.barh(range(101), f)
plt.show()

import matplotlib.pyplot as plt
plt.title('신도림 지역의 남녀 성별 인구 분포')
plt.barh(range(101), m, label = '남성')
plt.barh(range(101), f, label = '여성')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
plt.style.use('ggplot')
#plt.figure(figsize = (10,5), dpi=300)
plt.title('신도림 지역의 남녀 성별 인구 분포')
plt.barh(range(101), m, label = '남성')
plt.barh(range(101), f, label = '여성')
plt.legend()
plt.show()

import csv
f = open('gender.csv', encoding="cp949")
data = csv.reader(f)
 
m = []
f = []
 
name = input('찾고 싶은 지역의 이름을 알려주세요 : ')
for row in data :
    if name in row[0] :
        for i in row[3:104] :
            m.append(-int(i))
        for i in row[106:] :
            f.append(int(i))

import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.figure(figsize = (10,5), dpi=300)
plt.title(name + ' 지역의 남녀 성별 인구 분포')
plt.barh(range(101), m, label = '남성')
plt.barh(range(101), f, label = '여성')
plt.legend()
plt.show()

