# -*- coding: utf-8 -*-
"""using_korean_font.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5cnvRa3x3IN8XKwu4p1i2BE4zNm62uc

# Google Colab에서 한글 폰트 사용하는 코드

[`koreanize-matplotlib`](https://github.com/ychoi-kr/koreanize-matplotlib) 참고
"""

!pip install koreanize-matplotlib

import koreanize_matplotlib

"""## 잘 작동하는지 테스트 해보기"""

import matplotlib.pyplot as plt

plt.plot([10, 20, 30, 40], 'hotpink')
plt.title('한글 작동여부 테스트')
plt.show()